version: '3.1'

services:
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080
    store:
      image: postgres:14-alpine
      ports:
        - 8000:5432
      environment:
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "random"
        POSTGRES_DB: "dblab"
